services:
  nginx:
    image: nginx:1.26.2
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '127.0.0.1:50106:50106'
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  backend:
    build:
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    environment:
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      OAUTH2_CALLBACK_URI: ${OAUTH2_CALLBACK_URI}
      OAUTH2_ALLOWED_EMAILS: ${OAUTH2_ALLOWED_EMAILS}
      OAUTH2_SUCCESS_CALLBACK_URI: ${OAUTH2_SUCCESS_CALLBACK_URI}
      SESSION_COOKIE_SECRET: ${SESSION_COOKIE_SECRET}
    volumes:
      - ./sqlite:/node/sqlite
      - ${DATA_PATH}:/node/data

  sync:
    build:
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      - .env
    volumes:
      - ./sqlite:/node/sqlite
      - ${DATA_PATH}:/node/data
    command: npm run -w backend devSync

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=/
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
