FROM node:22

EXPOSE 50107

RUN mkdir /node
COPY ./package.json /node/
COPY backend/package.json /node/backend/package.json

WORKDIR /node
RUN npm i

COPY ./backend/src /node/backend/src


CMD npm run -w backend dev

